#!/usr/bin/env python3
"""Generate a MuJoCo MJCF for a simplified C. elegans body.

A 20-segment articulated chain intended to be the body substrate for
later Phase 2+ work — muscle-activation controllers (CPG / imitation /
connectome-constrained RL) and brain-body coupling.

Design choices:

- 20 rigid segments connected by 19 planar hinge joints (yaw around z).
  The adult hermaphrodite has thousands of cells but locomotion is
  dominated by dorsal-ventral muscle pairs along the anteroposterior
  axis; 20 segments captures the fundamental wave shape without
  overparameterising.
- Body length ~1 mm, width ~80 µm, aligned with the published
  adult hermaphrodite geometry.
- Per-joint angle limits roughly match the maximum curvature observed
  in crawling worms on agar (~0.5 rad per hinge).
- Each hinge joint has a single torque actuator. In the real worm each
  joint is driven by a dorsal + ventral muscle pair; the net torque is
  a valid low-dimensional projection for Phase 1.
- Viscous damping on joints approximates the hydrostatic stiffness +
  agar drag regime (low Reynolds number, inertia negligible).
- MJCF written to public/data/wormbody.xml so both MuJoCo Python
  tooling and future browser-side viewers (mujoco_wasm) can load it.

Reference anatomy: Cook et al. 2019 connectome paper's body
description; Boyle, Berri & Cohen 2012 neuromechanical model.
"""
from __future__ import annotations

from pathlib import Path


NUM_SEGMENTS = 20
# MuJoCo's mjMINVAL enforces a floor on body mass for numerical stability.
# A real adult worm is ~5 ng — below that floor — so the simulation is
# scaled up 1000× uniformly (real 1 mm body → 1 sim-m). Dynamics are
# scale-invariant within Newtonian physics; only the unit interpretation
# changes ("1 simulation metre corresponds to 1 real mm of worm body").
SEGMENT_LENGTH_M = 5.0e-2     # 50 sim-mm  (real: 50 µm)
SEGMENT_RADIUS_M = 4.0e-2     # 40 sim-mm  (real: 40 µm)
SUBSTRATE_CLEARANCE_M = 2 * SEGMENT_RADIUS_M
JOINT_RANGE_RAD = 0.5         # ±0.5 rad per hinge ≈ max observed curvature
JOINT_DAMPING = 0.001         # scaled damping
JOINT_STIFFNESS = 0.0         # muscles supply active torque; body is soft
ACTUATOR_GEAR = 0.001         # scales unit control command to realistic torque
ACTUATOR_CTRLRANGE = (-1.0, 1.0)
BODY_COLOR = "0.35 0.48 0.32 1"   # forest-greenish
HEAD_COLOR = "0.25 0.38 0.25 1"   # slightly darker for the head
SUBSTRATE_COLOR = "0.95 0.92 0.82 1"

OUT = Path(__file__).resolve().parents[1] / "public" / "data" / "wormbody.xml"


def _segment_color(index: int, total: int) -> str:
    return HEAD_COLOR if index == 0 else BODY_COLOR


def _render(num_segments: int) -> str:
    lines: list[str] = []
    push = lines.append

    push('<!-- Generated by scripts/build_wormbody.py. Edit the script, not this file. -->')
    push('<mujoco model="c_elegans_wormbody">')
    push('  <compiler angle="radian" autolimits="true"/>')
    push('  <option timestep="0.0005" integrator="implicitfast" viscosity="1.0e-3" density="1000"/>')
    push('  <visual>')
    push('    <headlight diffuse="0.8 0.8 0.8" ambient="0.3 0.3 0.3" specular="0.2 0.2 0.2"/>')
    push('    <global offwidth="1200" offheight="800"/>')
    push('  </visual>')
    push('  <default>')
    push(f'    <joint damping="{JOINT_DAMPING}" stiffness="{JOINT_STIFFNESS}" limited="true" range="{-JOINT_RANGE_RAD} {JOINT_RANGE_RAD}"/>')
    push('    <geom density="1000" friction="0.5 0.1 0.01"/>')
    push(f'    <motor ctrllimited="true" ctrlrange="{ACTUATOR_CTRLRANGE[0]} {ACTUATOR_CTRLRANGE[1]}" gear="{ACTUATOR_GEAR}"/>')
    push('  </default>')
    push('  <worldbody>')
    push(f'    <geom name="substrate" type="plane" size="0.01 0.01 0.001" rgba="{SUBSTRATE_COLOR}"/>')
    push('    <light name="overhead" pos="0 0 0.02" dir="0 0 -1" diffuse="0.8 0.8 0.8"/>')
    # Recursive segment tree — nest each new body inside the previous.
    indent = '    '
    push(
        f'{indent}<body name="segment_0" pos="0 0 {SUBSTRATE_CLEARANCE_M:.7f}" euler="0 0 0">'
    )
    indent = '      '
    push(f'{indent}<freejoint name="root"/>')
    push(
        f'{indent}<geom name="geom_0" type="capsule" '
        f'fromto="0 0 0 {SEGMENT_LENGTH_M:.7f} 0 0" size="{SEGMENT_RADIUS_M:.7f}" '
        f'rgba="{_segment_color(0, num_segments)}"/>'
    )
    for i in range(1, num_segments):
        prefix = indent + ('  ' * (i - 1)) if False else '      ' + '  ' * i
        push(
            f'{prefix}<body name="segment_{i}" pos="{SEGMENT_LENGTH_M:.7f} 0 0">'
        )
        inner = prefix + '  '
        push(
            f'{inner}<joint name="hinge_{i}" type="hinge" axis="0 0 1"/>'
        )
        push(
            f'{inner}<geom name="geom_{i}" type="capsule" '
            f'fromto="0 0 0 {SEGMENT_LENGTH_M:.7f} 0 0" size="{SEGMENT_RADIUS_M:.7f}" '
            f'rgba="{_segment_color(i, num_segments)}"/>'
        )
    # Close the nested <body> tags we opened.
    for i in range(num_segments - 1, 0, -1):
        close = '      ' + '  ' * i
        push(f'{close}</body>')
    push('      </body>')  # segment_0
    push('  </worldbody>')
    push('  <actuator>')
    for i in range(1, num_segments):
        push(f'    <motor name="muscle_{i}" joint="hinge_{i}"/>')
    push('  </actuator>')
    push('  <sensor>')
    for i in range(num_segments):
        push(f'    <framepos name="pos_segment_{i}" objtype="body" objname="segment_{i}"/>')
    push('  </sensor>')
    push('</mujoco>')

    return '\n'.join(lines) + '\n'


def main() -> None:
    xml = _render(NUM_SEGMENTS)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(xml)
    size_kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT} ({size_kb:.1f} KB, {NUM_SEGMENTS} segments, "
          f"{NUM_SEGMENTS - 1} hinges, {NUM_SEGMENTS - 1} muscle actuators)")


if __name__ == "__main__":
    main()
