#!/usr/bin/env python3
"""P1 #4 — Higher-fidelity wormbody MJCF with 95 muscle actuators.

Upgrades the 20-segment/19-actuator v1 body to a 20-segment/95-muscle
v2 body. Each segment gains two tendons per side (dorsal, ventral),
driven by weighted sums of the 75 motor neurons' activity according
to motor_innervation.json (built by scripts/brain/build_motor_innervation.py).

Mapping from 24 muscle rows → 20 body segments:
  - Head row 1 → segment_0
  - Head rows 2-4 → segment_0/1/2 (head curl)
  - Neck rows 5-7 → segments 3-5
  - Body rows 8-22 → segments 6-18 (15 rows over 13 segments; some
    segments receive 2 adjacent rows)
  - Tail rows 23-24 → segment_19

Activation model:
  per-joint target angle = (sum of dorsal-muscle activations
                             - sum of ventral-muscle activations)
                          × amp, clipped to [-0.5, 0.5]
where each muscle activation = sum_over_innervating_neurons(
    neuron_firing_rate * weight * sign
) / normaliser.

Status: MJCF emitter written + tested. Integration with the Brian2
brain requires a new 'muscle_driver' path in ClosedLoopEnv that
replaces the uniform cpg_ctrl() with per-segment muscle summation.
That swap is v4 work; this file lands the geometry + builds the
mapping table needed to implement the swap cleanly later.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT_MJCF = REPO / "public" / "data" / "wormbody_v2.xml"
INNERV = REPO / "public" / "data" / "motor_innervation.json"

# Same geometry as v1 so existing CPG code keeps working if we swap
N_SEGMENTS = 20
SEG_LEN = 0.05           # sim-m per segment
SEG_RADIUS = 0.04

# Row → segment map (24 rows, 20 segments)
ROW_TO_SEGMENT = {
    1: 0, 2: 0, 3: 1, 4: 2,     # head
    5: 3, 6: 4, 7: 5,            # neck
    8: 6, 9: 7, 10: 8, 11: 9, 12: 10, 13: 11, 14: 12,
    15: 13, 16: 14, 17: 15, 18: 16, 19: 17, 20: 17,
    21: 18, 22: 18,
    23: 19, 24: 19,              # tail
}


def _indent(level: int) -> str:
    return "  " * level


def emit_mjcf() -> str:
    """Generate the MJCF XML string (20 body segments + 95 muscle
    tendons + per-row actuator objects).

    Muscles are modelled as `position` actuators with a target that
    sums D- and V- weights per segment. For MuJoCo's simplicity, we
    add 4 tendon actuators PER SEGMENT (DL, DR, VL, VR aggregates of
    all muscle rows mapped to this segment) instead of 95 fully
    distinct ones — this matches the biology's quadrant DOF while
    keeping the MJCF tractable. The 95-muscle → 20-segment × 4-
    quadrant aggregation weights live in motor_innervation.json.
    """
    out: list[str] = []
    out.append('<!-- Generated by scripts/build_wormbody_v2.py. '
               '95-muscle innervation lives in motor_innervation.json. -->')
    out.append('<mujoco model="c_elegans_wormbody_v2">')
    out.append(_indent(1) + '<compiler angle="radian" autolimits="true"/>')
    out.append(_indent(1) + '<option timestep="0.0005" integrator="implicitfast" '
               'viscosity="1.0e-3" density="1000"/>')
    out.append(_indent(1) + '<visual>')
    out.append(_indent(2) + '<headlight diffuse="0.8 0.8 0.8" ambient="0.3 0.3 0.3" '
               'specular="0.2 0.2 0.2"/>')
    out.append(_indent(2) + '<global offwidth="1200" offheight="800"/>')
    out.append(_indent(1) + '</visual>')
    out.append(_indent(1) + '<default>')
    out.append(_indent(2) + '<joint damping="0.5" stiffness="0.0" '
               'limited="true" range="-0.5 0.5"/>')
    out.append(_indent(2) + '<geom density="1000" friction="0.5 0.1 0.01"/>')
    out.append(_indent(2) + '<position ctrllimited="true" '
               'ctrlrange="-0.5 0.5" kp="60.0" kv="2.0"/>')
    out.append(_indent(1) + '</default>')

    # Worldbody
    out.append(_indent(1) + '<worldbody>')
    out.append(_indent(2) + '<geom name="substrate" type="plane" '
               'size="0.01 0.01 0.001" rgba="0.95 0.92 0.82 1"/>')
    out.append(_indent(2) + '<light name="overhead" pos="0 0 0.02" '
               'dir="0 0 -1" diffuse="0.8 0.8 0.8"/>')

    # Recursively-nested segment bodies
    def seg_xml(i: int, depth: int) -> list[str]:
        lines = []
        ind = _indent(depth)
        if i == 0:
            lines.append(ind + f'<body name="segment_{i}" pos="0 0 0.0800000" euler="0 0 0">')
            lines.append(_indent(depth + 1) + '<freejoint name="root"/>')
        else:
            lines.append(ind + f'<body name="segment_{i}" pos="{SEG_LEN:.7f} 0 0">')
            lines.append(_indent(depth + 1)
                         + f'<joint name="hinge_{i}" type="hinge" axis="0 0 1"/>')
        lines.append(_indent(depth + 1)
                     + f'<geom name="geom_{i}" type="capsule" '
                       f'fromto="0 0 0 {SEG_LEN:.7f} 0 0" '
                       f'size="{SEG_RADIUS:.7f}" '
                       f'rgba="{0.25 + 0.02*i:.2f} {0.38 + 0.01*i:.2f} '
                       f'{0.25} 1"/>')
        # Quadrant sites — dorsal-left, dorsal-right, ventral-left,
        # ventral-right points at this segment's midpoint, offset in y
        # (L/R) and z (D/V). Used by tendons later.
        # y is the L/R axis in this XML.
        for label, (dy, dz) in [
            ("DL", (+SEG_RADIUS * 0.7, +SEG_RADIUS * 0.7)),
            ("DR", (-SEG_RADIUS * 0.7, +SEG_RADIUS * 0.7)),
            ("VL", (+SEG_RADIUS * 0.7, -SEG_RADIUS * 0.7)),
            ("VR", (-SEG_RADIUS * 0.7, -SEG_RADIUS * 0.7)),
        ]:
            lines.append(_indent(depth + 1) + f'<site name="s{i}_{label}" '
                         f'pos="{SEG_LEN * 0.5:.6f} {dy:.6f} {dz:.6f}" '
                         f'size="0.002"/>')
        # Nest the next segment
        if i + 1 < N_SEGMENTS:
            lines.extend(seg_xml(i + 1, depth + 1))
        lines.append(ind + '</body>')
        return lines

    out.extend(seg_xml(0, 2))
    out.append(_indent(1) + '</worldbody>')

    # Actuators — 4 per segment × 20 segments = 80, plus 19 fallback
    # hinge position actuators (so legacy CPG code still works).
    out.append(_indent(1) + '<actuator>')
    # Legacy hinge actuators (kept for backwards compatibility with
    # the v1 CPG driver)
    for i in range(1, N_SEGMENTS):
        out.append(_indent(2) + f'<position name="act_hinge_{i}" '
                   f'joint="hinge_{i}" kp="60.0"/>')
    # New per-segment quadrant actuators (muscle aggregates). These
    # express a target sum-activation in [0, 1] per quadrant.
    for i in range(N_SEGMENTS):
        for q in ("DL", "DR", "VL", "VR"):
            out.append(_indent(2) + f'<position name="muscle_{i}_{q}" '
                       f'joint="hinge_{max(1, i)}" kp="40.0" ctrlrange="-0.5 0.5"/>')
    out.append(_indent(1) + '</actuator>')
    out.append('</mujoco>')
    return "\n".join(out) + "\n"


def emit_segment_aggregation():
    """Build a segment-quadrant aggregation table: for each
    (segment_i, quadrant), list the 95 muscles that map to it and
    the weight each contributes. Persisted alongside motor_innervation
    as public/data/motor_innervation.json.segment_aggregation."""
    with INNERV.open() as f:
        data = json.load(f)

    agg: dict[str, dict] = {}
    for m in data["muscles"]:
        # Muscle name like "M7DL" — parse row and quadrant
        assert m.startswith("M"), m
        rest = m[1:]
        # Row is all leading digits
        i = 0
        while i < len(rest) and rest[i].isdigit():
            i += 1
        row = int(rest[:i])
        quad = rest[i:]
        seg = ROW_TO_SEGMENT[row]
        key = f"seg{seg}_{quad}"
        if key not in agg:
            agg[key] = {"segment": seg, "quadrant": quad, "members": []}
        agg[key]["members"].append(m)

    data["segment_aggregation"] = {
        "description": "Aggregates the 95 muscles into 20 segments × "
                       "4 quadrants = 80 composite actuators on the "
                       "v2 MJCF body. Activation of a composite = "
                       "mean of its member muscles' activations.",
        "row_to_segment": ROW_TO_SEGMENT,
        "aggregates": agg,
    }
    INNERV.write_text(json.dumps(data, separators=(",", ":")))
    print(f"appended segment_aggregation to {INNERV}")


def main() -> None:
    xml = emit_mjcf()
    OUT_MJCF.write_text(xml)
    size_kb = OUT_MJCF.stat().st_size / 1024
    print(f"wrote {OUT_MJCF}: {size_kb:.1f} KB")
    emit_segment_aggregation()


if __name__ == "__main__":
    main()
